### ISSUE TITLE
BuscaCEP.Providers.Correios.Utils

### ISSUE THREAD

**Issue by limelect** [antoniojmsjr/BuscaCEP#8]
No such pas file
BuscaCEP.Providers.Correios.Utils

**Comment by antoniojmsjr** [comment]
Is it generating any errors? The library uses the file *BuscaCEP.Providers.Correios.Utils.dcu* for compilation.

**Comment by limelect** [comment]
If you did not know dcu are per Delphi version
This dcu is not my version
Unless we have PAS file your software is usless

**Comment by antoniojmsjr** [comment]
Released in version [v2.1.0](https://github.com/antoniojmsjr/BuscaCEP/releases/tag/v2.1.0)

**Comment by limelect** [comment]
Thanks but errors as I compile with D10.2.3 so good luck

**Comment by antoniojmsjr** [comment]
> Thanks but errors as I compile with D10.2.3 so good luck

Thank you for the feedback! I have already made the necessary changes, and the minimum version is now Delphi 10 Seattle.
